In [167]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking'

In [168]:
DATA_PATH = os.path.join(BASE_DIR, 'input','parking_raw.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking\\input\\parking_raw.csv'

In [169]:
OUTPUT_PATH = os.path.join(BASE_DIR,'output','parking_long.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking\\output\\parking_long.csv'

In [170]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'

In [171]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [172]:
df_raw.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [173]:
df_raw.shape

(229, 27)

In [174]:
df_long = df_raw[['주차장명','소재지지번주소','주차구획수']]
df_long = df_long.reset_index(drop=True)

In [175]:
df_long.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

In [176]:
def df_long_PK(count):
    if count < 20:
        return '소형'
    elif count > 50 :
        return '대형'
    else:
        return '중형'
    
df_long['규모구분'] = df_long['주차구획수'].apply(df_long_PK)

df_long.head()

        주차장명               소재지지번주소  주차구획수 규모구분
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형

In [177]:
df_raw['요금정보']

0      무료
1      무료
2      무료
3      무료
4      무료
       ..
224    유료
225    유료
226    유료
227    유료
228    유료
Name: 요금정보, Length: 229, dtype: str

In [178]:
# df_long['요금정보'] = df_raw['요금정보'].copy
# df_long.head()

In [179]:
def df_long_money(fee):
    if fee=='무료':
        return '무료'
    else:
        return '유료'
    
df_long['fee_type'] = df_raw['요금정보'].apply(df_long_money)

df_long.head()

        주차장명               소재지지번주소  주차구획수 규모구분 fee_type
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형       무료
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형       무료
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형       무료
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형       무료
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형       무료

In [180]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine= create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('POSTGRESQL 연결 성공!')
        print(version[:80] + '...')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료! {saved_count:,}행')
    print(f'DB : parking_lot / table : {table_name}')

In [181]:
TABLE_NAME = 'subway_raw'

In [ ]:
save_to_postgresql(df_long,DB_URL,TABLE_NAME)

POSTGRESQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료! 229행
DB : parking_lot / table : subway_raw